[tool.ruff]
lint.extend-select = [
  "ANN",
  "C4",
  "COM",
  "I",
  "N",
  "PT",
  "RET",
  "SIM",
  "TCH",
  "TID",
]
lint.ignore = ["ANN002", "ANN003", "ANN101", "ANN102", "COM812"]
show-fixes = true
line-length = 100

[tool.ruff.lint.isort]
case-sensitive = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "core.settings"

[tool.djlint]
indent = 2
line_break_after_multiline_tag = true
blank_line_after_tag = "load,extends,include"
blank_line_before_tag = "load,extends,include"
preserve_blank_lines = true
close_void_tags = true
profile = "django"
max_line_length = 100
