# Generated by Django 4.2.10 on 2024-02-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_category_options_alter_priority_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("Job", "Job"),
                    ("Home", "Home"),
                    ("Shopping", "Shopping"),
                ],
                default="",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="priority",
            name="level",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("Low", "Low"),
                    ("Medium", "Mid"),
                    ("High", "High"),
                ],
                default="",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Undone"),
                    ("In progress", "In Progress"),
                    ("Done", "Done"),
                    ("Won't do", "Wont Do"),
                ],
                default="",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="todo.category",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="todo.priority",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="progress",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="todo.progress",
            ),
        ),
    ]
