# Generated by Django 4.2.10 on 2024-02-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_category_name_alter_priority_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
